### One-Hot Encoding


In [2]:
from sklearn.preprocessing import OneHotEncoder

import numpy as np


In [3]:
documents = [
    "the cat sat on the mat",
    "the dog sat on the mat",
    "the cat chased the dog",
    "the dog chased the cat"
]

In [8]:
vocabulary = set( word for doc in documents for word in doc.lower().split() )
vocabulary = list(vocabulary)
vocabulary

['on', 'the', 'sat', 'mat', 'cat', 'dog', 'chased']

In [14]:
vocabulary_array = np.array(vocabulary).reshape(-1, 1) # encoder expects 2D arraay as input

encoder = OneHotEncoder(sparse_output=False) # for easy interpretation we use sparse_output = False
# else we need to convert the sparse matrix to dense using .toarray() method
vector_values = encoder.fit_transform(vocabulary_array)

print(vector_values) #print(vector_values.toarray()) if sparse_output=True
print(encoder.categories_)


[[0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[array(['cat', 'chased', 'dog', 'mat', 'on', 'sat', 'the'], dtype='<U6')]


In [28]:
for doc in documents:
    for word in doc.lower().split():
        word_vector = encoder.transform([[word]])
        print(f"Word: {word}, Vector: {word_vector}")

Word: the, Vector: [[0. 0. 0. 0. 0. 0. 1.]]
Word: cat, Vector: [[1. 0. 0. 0. 0. 0. 0.]]
Word: sat, Vector: [[0. 0. 0. 0. 0. 1. 0.]]
Word: on, Vector: [[0. 0. 0. 0. 1. 0. 0.]]
Word: the, Vector: [[0. 0. 0. 0. 0. 0. 1.]]
Word: mat, Vector: [[0. 0. 0. 1. 0. 0. 0.]]
Word: the, Vector: [[0. 0. 0. 0. 0. 0. 1.]]
Word: dog, Vector: [[0. 0. 1. 0. 0. 0. 0.]]
Word: sat, Vector: [[0. 0. 0. 0. 0. 1. 0.]]
Word: on, Vector: [[0. 0. 0. 0. 1. 0. 0.]]
Word: the, Vector: [[0. 0. 0. 0. 0. 0. 1.]]
Word: mat, Vector: [[0. 0. 0. 1. 0. 0. 0.]]
Word: the, Vector: [[0. 0. 0. 0. 0. 0. 1.]]
Word: cat, Vector: [[1. 0. 0. 0. 0. 0. 0.]]
Word: chased, Vector: [[0. 1. 0. 0. 0. 0. 0.]]
Word: the, Vector: [[0. 0. 0. 0. 0. 0. 1.]]
Word: dog, Vector: [[0. 0. 1. 0. 0. 0. 0.]]
Word: the, Vector: [[0. 0. 0. 0. 0. 0. 1.]]
Word: dog, Vector: [[0. 0. 1. 0. 0. 0. 0.]]
Word: chased, Vector: [[0. 1. 0. 0. 0. 0. 0.]]
Word: the, Vector: [[0. 0. 0. 0. 0. 0. 1.]]
Word: cat, Vector: [[1. 0. 0. 0. 0. 0. 0.]]


In [29]:
testing_document = ["the cat sat on the mat", "the dog chased the cat"]

testing_vocabulary = list(set(word for doc in testing_document for word in doc.lower().split()))

testing_vectors = encoder.transform(np.array(testing_vocabulary).reshape(-1, 1))
print(testing_vocabulary)
print(testing_vectors)
print(encoder.categories_)

['on', 'the', 'sat', 'mat', 'cat', 'dog', 'chased']
[[0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]
[array(['cat', 'chased', 'dog', 'mat', 'on', 'sat', 'the'], dtype='<U6')]


#### checking out of vocabulary 

In [20]:
testing_document_2 = ["the cat sat on the mat", "the dog chased the cat", "the rabbit jumped"]

testing_vocabulary_2 = list(set(word for doc in testing_document_2 for word in doc.lower().split()))
print(testing_vocabulary_2)
print(encoder.categories_)

['jumped', 'on', 'the', 'sat', 'mat', 'rabbit', 'cat', 'dog', 'chased']
[array(['cat', 'chased', 'dog', 'mat', 'on', 'sat', 'the'], dtype='<U6')]


In [ ]:
testing_vectors_2 = encoder.transform(np.array(testing_vocabulary_2).reshape(-1, 1)) 
print(testing_vectors_2)

# since few words are not present in the training vocabulary, they will be ignored and not encoded.
# we will get value error if we try to encode a word that is not present in the training vocabulary.

### Bag Of Words
##### CountVectorizer and TfidfVectorizer, because they are designed to work directly with a list of text documents.

In [30]:
from sklearn.feature_extraction.text import CountVectorizer


In [34]:
BOW_vectorizer = CountVectorizer()
BOW_document_vectors = BOW_vectorizer.fit_transform(documents)
print(f'original documents : {documents}')
print(f'BOW vectors : {BOW_document_vectors.toarray()}')
print(f'Feature names : {BOW_vectorizer.get_feature_names_out()}')

['the cat sat on the mat', 'the dog sat on the mat', 'the cat chased the dog', 'the dog chased the cat']
[[1 0 0 1 1 1 2]
 [0 0 1 1 1 1 2]
 [1 1 1 0 0 0 2]
 [1 1 1 0 0 0 2]]
['cat' 'chased' 'dog' 'mat' 'on' 'sat' 'the']


##### Out of Vocabulary : do not usually raise the same kind of “out-of-vocabulary” error for unknown words the way OneHotEncoder does,instead, they simply ignore words that were not seen during fit

In [39]:
BOW_testing_document_2 = BOW_vectorizer.transform(testing_document_2)
print(f'testing documents : {testing_document_2}')
print(f'BOW vectors : {BOW_testing_document_2.toarray()}')
print(f'Feature names : {BOW_vectorizer.get_feature_names_out()}')

testing documents : ['the cat sat on the mat', 'the dog chased the cat', 'the rabbit jumped']
BOW vectors : [[1 0 0 1 1 1 2]
 [1 1 1 0 0 0 2]
 [0 0 0 0 0 0 1]]
Feature names : ['cat' 'chased' 'dog' 'mat' 'on' 'sat' 'the']


### TF-IDF

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer 

tfidf_vectorizer = TfidfVectorizer()

tifidf_vectors = tfidf_vectorizer.fit_transform(documents)
print(f'original documents : {documents}')
print(f'TF-IDF vectors : {tifidf_vectors.toarray()}')
print(f'Feature names : {tfidf_vectorizer.get_feature_names_out()}')


original documents : ['the cat sat on the mat', 'the dog sat on the mat', 'the cat chased the dog', 'the dog chased the cat']
TF-IDF vectors : [[0.34813837 0.         0.         0.43002015 0.43002015 0.43002015
  0.56925186]
 [0.         0.         0.34813837 0.43002015 0.43002015 0.43002015
  0.56925186]
 [0.40163007 0.49609304 0.40163007 0.         0.         0.
  0.6567178 ]
 [0.40163007 0.49609304 0.40163007 0.         0.         0.
  0.6567178 ]]
Feature names : ['cat' 'chased' 'dog' 'mat' 'on' 'sat' 'the']


### Out of Vocabulary : 

In [40]:
tfidf_testing_document_2 = tfidf_vectorizer.transform(testing_document_2)
print(f'testing documents : {testing_document_2}')
print(f'TF-IDF vectors : {tfidf_testing_document_2.toarray()}')
print(f'Feature names : {tfidf_vectorizer.get_feature_names_out()}')

testing documents : ['the cat sat on the mat', 'the dog chased the cat', 'the rabbit jumped']
TF-IDF vectors : [[0.34813837 0.         0.         0.43002015 0.43002015 0.43002015
  0.56925186]
 [0.40163007 0.49609304 0.40163007 0.         0.         0.
  0.6567178 ]
 [0.         0.         0.         0.         0.         0.
  1.        ]]
Feature names : ['cat' 'chased' 'dog' 'mat' 'on' 'sat' 'the']
